export const ROUTE_ROUTER = "ROUTE_ROUTER";
export const ROUTE_SCRATCH = "ROUTE_SCRATCH";

export const ROUTE_GESTURE = "ROUTE_GESTURE";
export const ROUTE_VOICE = "ROUTE_VOICE";

export const Z_INDEX_PREVIEW = 999;
export const Z_INDEX_NORMAL = 999;
export const Z_INDEX_WORKSPACE = 1;

export const RUN_PYTHON_STRING = "RUN_PYTHON_STRING";
export const RUN_PYTHON_RESULTS = "RUN_PYTHON_RESULTS";
export const RUN_PYTHON_ERR = "RUN_PYTHON_ERR"; // err
export const RUN_PYTHON_FINISHED = "RUN_PYTHON_FINISHED";