export const ROUTE_ROUTER = "ROUTE_ROUTER";
export const ROUTE_PROJECT_MANAGE = "ROUTE_PROJECT_MANAGE";
export const ROUTE_PROJECT_EDIT = "ROUTE_PROJECT_EDIT";

export const ROUTE_GESTURE = "ROUTE_GESTURE";
export const ROUTE_VOICE = "ROUTE_VOICE";

export const Z_INDEX_PREVIEW = 999;
export const Z_INDEX_NORMAL = 999;
export const Z_INDEX_WORKSPACE = 1;